version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - db-test-data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    expose:
      - "5432"
volumes:
  db-test-data:
